### ISSUE TITLE
The module health_check cannot be imported

### ISSUE THREAD

**Issue by tkn2023** [netbox-community/netbox-healthcheck-plugin#11]
### NetBox HealthCheck Plugin version

v0.1.2

### NetBox version

v3.7.4

### Python version

3.8

### Steps to Reproduce

install clean netbox.
Try installing healthcheck via pip
insert plugin in configuration.py
Run python3 manage.py collectstatic

### Expected Behavior

When running manage.py collectstatic there is no error and after restarting netbox service the netbox service should start and you can login.

### Observed Behavior

django.core.exceptions.ImproperlyConfigured: Failed to load django_apps specified by plugin netbox_healthcheck_plugin: ['health_check', 'health_check.db', 'health_check.contrib.migrations', 'health_check.contrib.redis', 'netbox_healthcheck_plugin.HealthCheckConfig'] The module health_check cannot be imported. Check that the necessary package has been installed within the correct Python environment.

**Comment by arthanson** [comment]
@tkn2023 thanks for noticing this, was missing a dependency in the pyproject filed - fixed with new release.
