### ISSUE TITLE
404 error

### ISSUE THREAD

**Issue by llamafilm** [netbox-community/netbox-healthcheck-plugin#9]
**NetBox version**
3.7.0

According to the readme file:
> NetBox exposes metrics at the /healthcheck HTTP endpoint, e.g. https://netbox.local/healthcheck.

But this endpoint returns 404 error.
<img width="505" alt="image" src="https://github.com/netbox-community/netbox-healthcheck-plugin/assets/3991046/69b86420-5c6a-494e-98fc-3858a0396f5c">

The `/plugins/netbox_healthcheck_plugin/healthcheck/` endpoint works correctly, so I believe this is a bug in the README.
<img width="1001" alt="image" src="https://github.com/netbox-community/netbox-healthcheck-plugin/assets/3991046/c0c31267-6b81-4e54-8433-d20208232212">

**Comment by abhi1693** [comment]
This is not a bug. If you want a separate endpoint, please open an FR instead, although I'm not sure if that would be accepted as plugins reside within the `plugins` namespace and I dont believe NetBox allows to override this behaviour.

**Comment by llamafilm** [comment]
According to the readme file:
> NetBox exposes metrics at the /healthcheck HTTP endpoint, e.g. https://netbox.local/healthcheck.

**Comment by olekgo** [comment]
Yes, this is confusing - the readme is incorrect, as it's true that plugins reside within the `plugins` namespace and it doesn't look like this behaviour can be overridden without (monkey) patching netbox itself.

**Comment by arthanson** [comment]
updated readme
